name: build-and-push

'on':
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_BASE: ghcr.io/${{ github.repository_owner }}/club

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # робимо тег у нижньому регістрі (GHCR цього вимагає)
      - name: Normalize image tag to lowercase
        run: echo "IMAGE_LC=$(echo '${IMAGE_BASE}' | tr '[:upper:]' '[:lower:]'):latest" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_LC }}
